
server:
  servlet:
    encoding:
      charset: utf-8
      force: true
  port: 8080

spring:
  datasource:
    # url: jdbc:h2:mem:test;MODE=MariaDB
    # driver-class-name: org.h2.Driver
    # username: sa
    # password:
    url: ${DATABASE_URL}localhost?allowPublicKeyRetrieval=true&useSSL=false
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: root
    
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      default_batch_fetch_size: 100
    open-in-view: false
  data:
    storage-type: redis
    redis:
      host: redis-service
      port: 6379
  mail:
    host: smtp.gmail.com
    port: 587
    username: ljh19980823@gmail.com
    password: yyzdbabwrmhhvyhi
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
jwt:
  secret: 7ZmA656AIOuTneygkOyZlSDquLDsm5AgMeydvOywqALdlsKJL3234jklsdjfaKJDLnflkasdf

logging:
  level:
    '[com.example.kakao]': DEBUG
    '[org.hibernate.type]': TRACE



# spring:
#   datasource:
#       url: jdbc:h2:mem:test;MODE=MariaDB
#         driver-class-name: org.h2.Driver
#         username: sa
#         password:
    # url: localhost?allowPublicKeyRetrieval=true&useSSL=false
    # driver-class-name: org.mariadb.jdbc.Driver
    # username: root
    # password: root
#   jpa:
#     hibernate:
#       ddl-auto: create
#     show-sql: true
#     properties:
#       hibernate:
#         format_sql: true
#       default_batch_fetch_size: 100
#     open-in-view: false
#   data:
#     storage-type: redis
#     redis:
#       host: localhost
#       port: 6379
